---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: homelab-k8s
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: homelab-k8s
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.244.0.0/16  # Pod network (Cilium)
    services:
      cidrBlocks:
        - 10.96.0.0/12   # Service network
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: homelab-k8s-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: VSphereCluster
    name: homelab-k8s

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereCluster
metadata:
  name: homelab-k8s
  namespace: default
spec:
  controlPlaneEndpoint:
    host: 192.168.1.100  # Static IP for API server (update for your network)
    port: 6443
  identityRef:
    kind: Secret
    name: vsphere-creds
  server: vcenter.homelab.local  # Update with your vCenter FQDN
  thumbprint: ""  # Update with your vCenter SSL thumbprint from step 7
  # Example: "6E:C4:92:E3:F1:A2:B5:C8:D9:E0:F1:A2:B3:C4:D5:E6:F7:A8:B9:C0:D1:E2:F3:A4:B5:C6:D7:E8:F9:A0:B1:C2"

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereClusterIdentity
metadata:
  name: homelab-vsphere-identity
  namespace: default
spec:
  secretName: vsphere-creds
  allowedNamespaces:
    selector:
      matchLabels: {}

---
apiVersion: v1
kind: Secret
metadata:
  name: vsphere-creds
  namespace: default
type: Opaque
stringData:
  username: k8s-capv@vsphere.local  # Update with your vSphere username
  password: your-vsphere-password-here  # IMPORTANT: Use sealed-secrets or external secrets in production!

---
# Storage configuration for vSphere CSI
apiVersion: v1
kind: ConfigMap
metadata:
  name: vsphere-cloud-config
  namespace: default
data:
  vsphere.conf: |
    [Global]
    cluster-id = "homelab-k8s"

    [VirtualCenter "vcenter.homelab.local"]
    insecure-flag = "true"  # Set to false with valid SSL cert
    datacenters = "Datacenter"

    [Workspace]
    server = "vcenter.homelab.local"
    datacenter = "Datacenter"
    default-datastore = "datastore1"
    resourcepool-path = "k8s-homelab"
    folder = "k8s-homelab"

    [Disk]
    scsicontrollertype = pvscsi

    [Network]
    public-network = "VM Network"
