---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: homelab-k8s-control-plane
  namespace: default
spec:
  replicas: 1  # Single control plane for homelab (increase to 3 for HA)
  version: v1.28.5
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: VSphereMachineTemplate
      name: homelab-k8s-control-plane-template
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
          enable-admission-plugins: NodeRestriction,PodSecurityPolicy
        timeoutForControlPlane: 10m
      controllerManager:
        extraArgs:
          cloud-provider: external
          allocate-node-cidrs: "false"  # Cilium manages pod CIDR
      dns:
        imageRepository: registry.k8s.io/coredns
        imageTag: v1.10.1
      etcd:
        local:
          dataDir: /var/lib/etcd
          extraArgs:
            quota-backend-bytes: "8589934592"  # 8GB quota for etcd
      imageRepository: registry.k8s.io
      networking:
        dnsDomain: cluster.local
        podSubnet: 10.244.0.0/16
        serviceSubnet: 10.96.0.0/12
    initConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cloud-provider: external
          tls-cipher-suites: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        name: "{{ ds.meta_data.hostname }}"
    joinConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cloud-provider: external
          tls-cipher-suites: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        name: "{{ ds.meta_data.hostname }}"
    preKubeadmCommands:
      # Disable swap (required for kubelet)
      - swapoff -a
      - sed -i '/ swap / s/^/#/' /etc/fstab
      # Load kernel modules for Cilium
      - modprobe overlay
      - modprobe br_netfilter
      # Sysctl settings for Kubernetes
      - sysctl -w net.ipv4.ip_forward=1
      - sysctl -w net.bridge.bridge-nf-call-iptables=1
      - sysctl -w net.bridge.bridge-nf-call-ip6tables=1
    postKubeadmCommands:
      # Wait for kubelet to be ready
      - while [ ! -f /etc/kubernetes/admin.conf ]; do sleep 1; done
    files:
      # Containerd config with SystemdCgroup enabled
      - path: /etc/containerd/config.toml
        owner: root:root
        permissions: "0644"
        content: |
          version = 2
          [plugins]
            [plugins."io.containerd.grpc.v1.cri"]
              sandbox_image = "registry.k8s.io/pause:3.9"
              [plugins."io.containerd.grpc.v1.cri".containerd]
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
                  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                    runtime_type = "io.containerd.runc.v2"
                    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                      SystemdCgroup = true
              [plugins."io.containerd.grpc.v1.cri".registry]
                [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
                  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
                    endpoint = ["https://registry-1.docker.io"]

      # Sysctl settings persistence
      - path: /etc/sysctl.d/99-kubernetes.conf
        owner: root:root
        permissions: "0644"
        content: |
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.conf.all.forwarding = 1
          net.ipv6.conf.all.forwarding = 1

      # Kernel modules for container networking
      - path: /etc/modules-load.d/k8s.conf
        owner: root:root
        permissions: "0644"
        content: |
          overlay
          br_netfilter

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  name: homelab-k8s-control-plane-template
  namespace: default
spec:
  template:
    spec:
      cloneMode: linkedClone  # Faster provisioning with linked clones
      datacenter: Datacenter
      datastore: datastore1
      diskGiB: 50
      folder: k8s-homelab
      memoryMiB: 8192  # 8GB RAM for control plane
      network:
        devices:
          - dhcp4: true
            networkName: VM Network
      numCPUs: 2
      os: linux
      powerOffMode: trySoft
      resourcePool: k8s-homelab
      server: vcenter.homelab.local
      storagePolicyName: ""  # Leave empty for default storage policy
      template: flatcar-stable  # Update to match your Flatcar template name in content library
      thumbprint: ""  # Same thumbprint as cluster.yaml
